"""add search court_decisions participants norms

Revision ID: ca22895b531d
Revises: 
Create Date: 2026-04-22 10:23:57.876137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca22895b531d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_court_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=20), nullable=False),
    sa.Column('case_number', sa.Text(), nullable=False),
    sa.Column('court_name', sa.Text(), nullable=False),
    sa.Column('court_type', sa.String(length=20), nullable=False),
    sa.Column('instance_level', sa.Integer(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('judges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('appeal_status', sa.String(length=30), nullable=True),
    sa.Column('dispute_type', sa.String(length=30), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('claim_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('minio_path', sa.Text(), nullable=True),
    sa.Column('es_indexed', sa.Boolean(), nullable=False),
    sa.Column('qdrant_indexed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_hash')
    )
    op.create_index(op.f('ix_search_court_decisions_case_number'), 'search_court_decisions', ['case_number'], unique=False)
    op.create_index(op.f('ix_search_court_decisions_decision_date'), 'search_court_decisions', ['decision_date'], unique=False)
    op.create_table('search_decision_norms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=False),
    sa.Column('law_name', sa.Text(), nullable=False),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('part', sa.Text(), nullable=True),
    sa.Column('paragraph', sa.Text(), nullable=True),
    sa.Column('raw_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['search_court_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_decision_norms_decision_id'), 'search_decision_norms', ['decision_id'], unique=False)
    op.create_table('search_decision_participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['search_court_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_decision_participants_decision_id'), 'search_decision_participants', ['decision_id'], unique=False)
    op.create_index(op.f('ix_search_decision_participants_inn'), 'search_decision_participants', ['inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_decision_participants_inn'), table_name='search_decision_participants')
    op.drop_index(op.f('ix_search_decision_participants_decision_id'), table_name='search_decision_participants')
    op.drop_table('search_decision_participants')
    op.drop_index(op.f('ix_search_decision_norms_decision_id'), table_name='search_decision_norms')
    op.drop_table('search_decision_norms')
    op.drop_index(op.f('ix_search_court_decisions_decision_date'), table_name='search_court_decisions')
    op.drop_index(op.f('ix_search_court_decisions_case_number'), table_name='search_court_decisions')
    op.drop_table('search_court_decisions')
    # ### end Alembic commands ###
